# Generated by Django 3.0.5 on 2020-08-16 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='fees_in_usa',
            field=models.PositiveSmallIntegerField(default=0, help_text='указать сумму в долларах', verbose_name='Сборы в США'),
        ),
    ]
